print("My name is Salma")
print("My age is 21 years old")
print("My department is Electronics and communication")
print("My graduation year: 2024")
print("My favorite team: Software")
print("Mind cloud fooo2 <3")
print("second commit in feature")
